default_platform(:ios)

platform :ios do
  desc "Bump version number"
  lane :bump do
    set_info_plist_value(path: ENV['PROJECT_PATH'], key: "CFBundleShortVersionString", value:ENV['MARKET_VERSION'] )
  end
end
